### ISSUE TITLE
Yuri has a token identification issue

### ISSUE THREAD

**Issue by sayori3** [sayori3/dokis#40]
valid tokens are rejected by Yuri claiming "invalid token"

```atic_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 547, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 510, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 376, in login
    await self.http.static_login(token, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.```

**Comment by tangalbert919** [comment]
Did you regenerate Yuri's token, and then copy that into the `token` setting in the config?

**Comment by sayori3** [comment]
Why do I need to regenerate it, the current token is valid

**Comment by sayori3** [comment]
epic, some jack changed my token, nice.
